# Streamlit configuration file
# This file customizes the appearance and behavior of your Streamlit app


[theme]
#Color theme - you can change these to customize the look
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
# Server settings
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser settings
gatherUsageStats = false
